services:
  val0:
    hostname: val0
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val0
    volumes:
      - ./config/volumes/node0:/etc/opt/ripple/
      # - ./config/health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--start", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      # test: ["CMD", "/health.sh"]
      interval: 10s
      timeout: 10s
      retries: 5
    # networks:
    #   rippled-net:
        # ipv4_address: 10.0.0.3

  val1:
    hostname: val1
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val1
    volumes:
      - ./config/volumes/node1:/etc/opt/ripple
      - ./config/health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "/health.sh"]
      interval: 40s
      timeout: 10s
      retries: 5
    # networks:
    #   rippled-net:
        # ipv4_address: 10.0.0.4

  val2:
    hostname: val2
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val2
    volumes:
      - ./config/volumes/node2:/etc/opt/ripple
      - ./config/health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "/health.sh"]
      interval: 40s
      timeout: 10s
      retries: 5
    # networks:
    #   rippled-net:
        # ipv4_address: 10.0.0.5

  val3:
    hostname: val3
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val3
    volumes:
      - ./config/volumes/node3:/etc/opt/ripple
      - ./config/health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/health.sh"]
      interval: 40s
      timeout: 10s
      retries: 5
    # networks:
    #   rippled-net:
        # ipv4_address: 10.0.0.6

  val4:
    hostname: val4
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val4
    volumes:
      - ./config/volumes/node4:/etc/opt/ripple
      - ./config/health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/health.sh"]
      interval: 40s
      timeout: 10s
      retries: 5
    # networks:
    #   rippled-net:
        # ipv4_address: 10.0.0.7

  val5:
    hostname: val5
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val5
    volumes:
      - ./config/volumes/node5:/etc/opt/ripple
      - ./config/health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/health.sh"]
      interval: 40s
      timeout: 10s
      retries: 5
    # networks:
    #   rippled-net:
        # ipv4_address: 10.0.0.8

  rippled:
    hostname: rippled
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: rippled
    ports:
      - 0.0.0.0:5005:5005
      - 0.0.0.0:6005:6005
    volumes:
    # - ./volumes/workload/:/root
    - ./config/volumes/rippled/:/etc/opt/ripple
    depends_on:
      val0:
          condition: service_healthy
      val1:
          condition: service_healthy
      val2:
          condition: service_healthy
      val3:
          condition: service_healthy
      val4:
          condition: service_healthy
      val5:
          condition: service_healthy
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    # command: ["/usr/bin/bash", "-c", "/root/run_tests.sh val0 val1 val2 val3 val4 val5"]
    # working_dir: /root
    # healthcheck:
    #   test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    # networks:
    #   rippled-net:
        # ipv4_address: 10.0.0.9

  workload:
    hostname: workload
    init: true
    image: workload_container_test
    container_name: workload
    # volumes:
    # - ./volumes/workload/:/root
    # - ./volumes/rippled/:/etc/opt/ripple
    # command: ["/usr/bin/bash", "-c", "/root/run_tests.sh val0 val1 val2 val3 val4 val5"]
    # working_dir: /root
    # healthcheck:
    #   test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    # networks:
    #   rippled-net:
    #     ipv4_address: 10.0.0.10

# networks:
#   rippled-net:
#     name: rippled-net
#     driver: bridge
#     ipam:
#       config:
#       - subnet: 10.0.0.0/24
