test-ubuntu-20:
  stage: test
  script:
      - . install_rippled.sh --jobID "$CI_JOB_ID" --jobName "$job_name" --network "$network" --product "$product" --publishStats "$publish_stats" --mode "$install_mode" --rippledVersion "$rippled_version" --standaloneMode "$standalone_mode" --feature "$feature" --rippledRemoteBranch "$rippled_remote_branch" --witnessRemoteBranch "$witness_remote_branch" --sidechainAutoSubmit "$sidechain_auto_submit" --slackNotify "$slack_notify"
      - . run_test.sh --jobID "$CI_JOB_ID" --jobName "$job_name" --jobOwner "$job_owner" --hostname "$host_name" --port "$port" --clioHost "$clio_host" --clioPort "$clio_port" --network "$network" --runType "$type" --standaloneMode "$standalone_mode" --testFilter "$test_filter" --publishTestResults "$publish_test_results" --publishStats "$publish_stats" --useWebsockets "$use_websockets" --websocketsPort "$websockets_port" --xchainBridgeCreate "$xchain_bridge_create" --slackNotify "$slack_notify"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always
  image:
    name: artifactory.ops.ripple.com/ubuntu:22.04
  tags:
    - xrpledger,high-iops
  artifacts:
    when: always
    paths:
      - logs/
    reports:
      junit: "logs/test_results/*test_results.xml"
  after_script:
    - . scripts/post_run.sh
