services:
  val0:
    hostname: val0
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val0
    volumes:
      - ./volumes/node0:/etc/opt/ripple/
    command: rippled --start
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  val1:
    hostname: val1
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val1
    volumes:
      - ./volumes/node1:/etc/opt/ripple
      - ./health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "/health.sh"]
      start_period: 50s
      interval: 5s
      timeout: 60s
      retries: 5

  val2:
    hostname: val2
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val2
    volumes:
      - ./volumes/node2:/etc/opt/ripple
      - ./health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "/health.sh"]
      start_period: 50s
      interval: 5s
      timeout: 60s
      retries: 5

  val3:
    hostname: val3
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val3
    volumes:
      - ./volumes/node3:/etc/opt/ripple
      - ./health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/health.sh"]
      start_period: 50s
      interval: 5s
      timeout: 60s
      retries: 5

  val4:
    hostname: val4
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val4
    volumes:
      - ./volumes/node4:/etc/opt/ripple
      - ./health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/health.sh"]
      start_period: 50s
      interval: 5s
      timeout: 60s
      retries: 5

  val5:
    hostname: val5
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: val5
    volumes:
      - ./volumes/node5:/etc/opt/ripple
      - ./health.sh:/health.sh
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    depends_on:
      val0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/health.sh"]
      start_period: 50s
      interval: 5s
      timeout: 60s
      retries: 5

  rippled:
    hostname: rippled
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: ${IMAGE}
    container_name: rippled
    ports:
      - 0.0.0.0:5005:5005
      - 0.0.0.0:6005:6005
    volumes:
    - ./volumes/rippled/:/etc/opt/ripple
    - ./health.sh:/health.sh
    depends_on:
      val0:
          condition: service_healthy
      val1:
          condition: service_healthy
      val2:
          condition: service_healthy
      val3:
          condition: service_healthy
      val4:
          condition: service_healthy
      val5:
          condition: service_healthy
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/health.sh"]
      start_period: 50s
      interval: 5s
      timeout: 60s
      retries: 5

  workload:
    hostname: workload
    init: true
    build:
      context: ./volumes/workload/
      # dockerfile: ./volumes/workload/Dockerfile
    depends_on:
      rippled:
        condition: service_healthy
    image: legleux/antithesis_workload_new_test
    container_name: workload
