services:
  rippled:
    hostname: rippled
    image: rippled:antithesis
    container_name: rippled
    volumes:
        - ./configs/rippled/:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:

  val0:
    hostname: validator_0
    image: rippled:antithesis
    container_name: val0
    volumes:
        - ./configs/node0:/etc/opt/ripple/
    command: ["/opt/ripple/bin/rippled", "--start", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:

  val1:
    hostname: validator_1
    image: rippled:antithesis
    container_name: val1
    volumes:
        - ./configs/node1:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:

  val2:
    hostname: validator_2
    image: rippled:antithesis
    container_name: val2
    volumes:
        - ./configs/node2:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:

  val3:
    hostname: validator_3
    image: rippled:antithesis
    container_name: val3
    volumes:
        - ./configs/node3:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:

  val4:
    hostname: validator_4
    image: rippled:antithesis
    container_name: val4
    volumes:
        - ./configs/node4:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:

  val5:
    hostname: validator_5
    image: rippled:antithesis
    container_name: val5
    volumes:
        - ./configs/node5:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:

networks:
  rippled-net:
    name: rippled-net
